version: "3.7"
services:
  postgres:
    image: "postgres:12-alpine"
    environment:
      - POSTGRES_USER=folio_admin
      - POSTGRES_PASSWORD=folio_admin
      - POSTGRES_DB=okapi_modules
    ports:
      - "5432:5432"
    volumes:
      - ./okapi-db-init.sql:/docker-entrypoint-initdb.d/okapi-db-init.sql
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
      - "29092:29092"
    hostname: kafka
    environment:
      KAFKA_LISTENERS: INTERNAL://:29092,LOCAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:29092,LOCAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LOCAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_RETENTION_BYTES: -1
      KAFKA_LOG_RETENTION_HOURS: -1
    depends_on:
      - zookeeper

networks: 
  default: 
    name: folio_network
